### ISSUE TITLE
Adding the TTS remap to Snips plugin

### ISSUE THREAD

**Issue by CoorFun** [KiboOst/SNIPS-Tips#1]
Hi Kiboost, 

I am currently working on the new release of plugin. 

I wonder that it could be great to integrate your remap code to the next release.. 

I would know your opinion about this idea. If you are willing to share this with us and If you would do the job by a pull request?

Also I do not understand why you need ssh username and password for this script 😂

**Comment by KiboOst** [comment]
Hi,

No problem to share my code, if it can help, nice.
Don't think I will have to time soon to make a PR anyway

For ssh code, you're right, that was for other functions I have in a more complete scripts in production. Have remove it.

**Comment by CoorFun** [comment]
Hi,

Good to have the approvement. I will then manage to integrate this great idea for the next release!
